### PR TITLE
Added left and right gravity

### PR DESCRIPTION
**Pull request by akihiro0228**
Added left and right gravities.

easydialogdemo

### CODE REVIEW

**Comment by michaelye** [comment]
@akihiro0228 Very nice feature,Thanks for this PR :100:

**Comment by enenla** [comment]
Thanks! :+1:

**Comment by michaelye** [comment]
@akihiro0228 
I modify the README.md file 

see: https://github.com/michaelye/EasyDialog/blob/master/README.md

And if you don't mind ,I want to added a link to your github address like this : )

**Comment by enenla** [comment]
No problem :+1:

**Comment by michaelye** [comment]
@akihiro0228 :ok_hand:

**Pull request merged**
